from __future__ import annotations

from datetime import datetime
from pathlib import Path


def build_markdown_report(metadata: dict[str, str], brief_markdown: str) -> str:
    """Return the generated brief with a lightweight generated timestamp."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"{brief_markdown.strip()}\n\n---\n_Generated by Meeting Prep Copilot v1 on {generated_at}._\n"


def safe_report_filename(client_name: str, meeting_title: str) -> str:
    """Create a safe filename for the Markdown download."""
    base = f"{client_name}_{meeting_title}".strip("_") or "meeting_brief"
    safe = "".join(character if character.isalnum() else "_" for character in base)
    safe = "_".join(part for part in safe.split("_") if part)
    return f"{safe.lower()}_brief.md"


def save_report(report_markdown: str, filename: str, output_dir: str = "outputs") -> Path:
    """Persist a copy locally for convenience during demos."""
    path = Path(output_dir)
    path.mkdir(exist_ok=True)
    output_path = path / filename
    output_path.write_text(report_markdown, encoding="utf-8")
    return output_path
